services:

  ccf_sandbox:
    image: ghcr.io/microsoft/ccf/app/dev/virtual:latest
    build:
      dockerfile: Dockerfile
      args:
        - CCF_PLATFORM=virtual
    command: /opt/ccf_virtual/bin/sandbox.sh --http2
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-k", "--fail", "https://localhost:8000/node/network"]
      interval: 1s
      retries: 120
    volumes:
      - ${CCF_WORKSPACE:-./}:/workspace
