name: C-ACI System Tests

permissions:
   id-token: write
   contents: read

on:
  workflow_dispatch:
    inputs:
      pytest_path:
        type: string
        description: "The path to tests to run in C-ACI"
  workflow_call:
    inputs:
      pytest_path:
        type: string
        description: "The path to tests to run in C-ACI"

jobs:
  aci-system-test:
    name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install c_aci_testing package
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/install-c-aci-testing.sh

      - name: Setup Docker
        run: sudo usermod -aG docker $USER

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MANAGED_ID_CLIENT_ID }}
          tenant-id: ${{ secrets.MANAGED_ID_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Run tests in C-ACI
        env:
          TEST_ENVIRONMENT: cloud
        run: |
          pip install -r requirements.txt
          pytest -s test/system-test/${{ inputs.pytest_path }}