name: Endpoint Test

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      endpoint:
        type: string
  workflow_call:
    inputs:
      endpoint:
        type: string

jobs:

  endpoint:
    name: ${{ inputs.endpoint }} (${{ matrix.env }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [ccf/sandbox-local]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MANAGED_ID_CLIENT_ID }}
          tenant-id: ${{ secrets.MANAGED_ID_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Install Dependencies
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/tools/install-deps.sh

      - name: Run System Tests
        env:
            TEST_ENVIRONMENT: ${{ matrix.env }}
        run: |
          if [ "${{ inputs.endpoint }}" == "heartbeat" ]; then
            source ./scripts/ccf/sandbox-local/up.sh
            source ./scripts/kms/js-app-set.sh
            source ./scripts/kms/endpoints/heartbeat.sh
            source ./scripts/ccf/sandbox-local/down.sh
          fi
          pytest -sv test/system-test/test_${{ inputs.endpoint }}.py
