name: System Tests

permissions:
   id-token: write
   contents: read

on:
  workflow_dispatch:
  workflow_call:

jobs:
  local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run Local System Tests
        run: pytest -sv test/system-test

  # c-aci-heartbeat:
  #   name: c-aci
  #   secrets: inherit # pragma: allowlist secret
  #   uses: ./.github/workflows/c_aci_system_tests.yml
  #   with:
  #     pytest_path: test_heartbeat.py

  # c-aci-key:
  #   name: c-aci
  #   secrets: inherit # pragma: allowlist secret
  #   uses: ./.github/workflows/c_aci_system_tests.yml
  #   with:
  #     pytest_path: test_key.py

  # c-aci-keyReleasePolicy:
  #   name: c-aci
  #   secrets: inherit # pragma: allowlist secret
  #   uses: ./.github/workflows/c_aci_system_tests.yml
  #   with:
  #     pytest_path: test_keyReleasePolicy.py

  # c-aci-listpubkeys:
  #   name: c-aci
  #   secrets: inherit # pragma: allowlist secret
  #   uses: ./.github/workflows/c_aci_system_tests.yml
  #   with:
  #     pytest_path: test_listpubkeys.py

  # c-aci-pubkey:
  #   name: c-aci
  #   secrets: inherit # pragma: allowlist secret
  #   uses: ./.github/workflows/c_aci_system_tests.yml
  #   with:
  #     pytest_path: test_pubkey.py

  # c-aci-refresh:
  #   name: c-aci
  #   secrets: inherit # pragma: allowlist secret
  #   uses: ./.github/workflows/c_aci_system_tests.yml
  #   with:
  #     pytest_path: test_refresh.py
